### ISSUE TITLE
[Bug] L2 standalone runner: worker.register() fails because _create_worker() returns a raw ChipWorker (regression from #710)

### ISSUE THREAD

**Issue by ChaoZheng109** [ChaoWao/simpler#744]
### Platform

All / Unknown

### Runtime Variant

All / Unknown

### Description

The standalone test runner path (`python <test>.py -p <platform>`) is broken for any L2 `SceneTestCase` after #710. The first per-class case fails with:

```
'ChipWorker' object has no attribute 'register'
```

`simpler_setup/scene_test.py:940` (introduced by #710, c3c1ce0f) calls `worker.register(callable_obj)` inside the L2 fallback registration block. Two entry points feed this code with different worker types:

| Entry point | Worker source | Type | Has `register`? |
| --- | --- | --- | --- |
| pytest + `st_worker` fixture (`conftest.py:899`) | `from simpler.worker import Worker` | `Worker` (high-level wrapper) | yes (`python/simpler/worker.py:668`) |
| Standalone runner — `_create_standalone_worker` L2 branch (`simpler_setup/scene_test.py:1591-1594`) → `first_cls._create_worker()` (`simpler_setup/scene_test.py:808-814`) | `from simpler.task_interface import ChipWorker` | `ChipWorker` (raw nanobind binding) | no — only `prepare_callable` (`python/simpler/task_interface.py:296`) |

CI runs only the pytest path, so the regression slipped through. The standalone runner is silently broken on `main`.

### Steps to Reproduce

```bash
source .venv/bin/activate
python examples/a5/tensormap_and_ringbuffer/paged_attention_unroll_manual_scope/test_paged_attention_unroll.py -p <platform>
```

Any L2 `SceneTestCase` reproduces it (runtime variant doesn't matter; the failing line is runtime-agnostic).

### Expected Behavior

Standalone runner registers the callable, executes the case, and prints `PASSED` (or a genuine numerical/runtime failure). It should behave equivalently to the pytest path for L2.

### Actual Behavior

```
=== Runtime: tensormap_and_ringbuffer  Level: 2 ===
  TestPagedAttentionUnroll::Case1 ... [...][INFO_V0] finalize: [device_runner.cpp:1256] DeviceRunner finalized
FAILED: 'ChipWorker' object has no attribute 'register'
```

The AttributeError comes from `simpler_setup/scene_test.py:940`:

```python
cid = getattr(type(self), "_st_l2_cid", None)
if cid is None:
    cid = worker.register(callable_obj)   # <-- ChipWorker has no .register
```

### Git Commit ID

0c3e3c96b2b073e5a591f775ceaae678985f9b86

### Host Platform

Linux (aarch64)

### Additional Context

**Suggested fixes (in order of cleanliness):**

1. **Add `ChipWorker.register(target) -> int`** that allocates a cid (process-local counter) and internally calls `prepare_callable(cid, target)`. This unifies the L2/L3 API per #710's stated intent ("Worker.register(target) -> cid is the single entry point for sub-fn / orch-fn / ChipCallable at every level"). Both `Worker` and the standalone path then go through the same method.
2. Make `_create_standalone_worker` return a `simpler.worker.Worker` for L2 instead of a bare `ChipWorker`, matching what `st_worker` does.
3. Quick fix: inline cid allocation + `prepare_callable` in `scene_test.py:940`.

**Also:** add a CI smoke that exercises the standalone runner on at least one L2 case, so future divergences between the two entry points are caught.

**Owners:** `simpler_setup/scene_test.py`, `python/simpler/worker.py`, `python/simpler/task_interface.py` (#710 author).

**Comment by ChaoZheng109** [comment]
fixed by #749
